Update ja.json
Bl4Cc4t/GoodTwitter2 pull request #289
Opened 2021-04-17 10:08 UTC by Gizel-jiz

Translation of "tweetIconsPullLeft" .

Also, I don't know what the function of "settingsHeaderGlobalStyling" is, so I can't translate it.
What is this function?
I think it's something to do with headers...

2021-04-17 22:26 UTC, Bl4Cc4t commented
Oh, I'm sorry that it isn't easy to understand. I rearranged the settings a bit and put them into more categories, so it's easier to find them.
`settingsHeaderGlobalStyling` is the hea
![image](https://user-images.githubusercontent.com/6740726/115128236-ab455000-9fdc-11eb-8d24-3ce10cb2809a.png)

2021-04-18 03:52 UTC, Gizel-jiz commented
Thank you for the detailed information with pictures.
I've just updated it.

However, I couldn't think of a good Japanese translation for "Global Styling", so I couldn't translate it well, and it may have come out a bit unnatural... :(

2021-04-18 09:35 UTC, Bl4Cc4t commented
Hm, I think "Global Styling" really sounds a bit weird. What do you think of "Global Look"? I think that sounds better, I think I should change it to that.

2021-04-18 16:05 UTC, Gizel-jiz commented
Hmm...
It's true that "Global Look" is easier to convey than "Global Styling", and it's easier to translate into Japanese.
I had a little trouble translating "Styling" into good Japanese when I was translating it. : /
So, I personally think it would be better to change it to "Global Look" : )

2021-04-20 16:13 UTC, Gizel-jiz commented
Thank you for modified!
The Japanese translation of "Global Look" has just been updated.  : )

2021-04-20 20:46 UTC, Bl4Cc4t requested changes
The `*NEW*` parts in the strings are only internally used, so that it's more obvious to notice what new parts were added and need to be translated. 
I think I have to add that to the documentation and take a better look at the changes next time...

Related: https://github.com/Bl4Cc4t/GoodTwitter2/pull/108#issuecomment-643733694

2021-04-20 20:46 UTC, Bl4Cc4t commented on i18n/ja.json
> +  "settingsHeaderGlobalLook": "*NEW* 全体的な見た目",
```suggestion
  "settingsHeaderGlobalLook": "全体的な見た目",
```

2021-04-20 20:46 UTC, Bl4Cc4t commented on i18n/ja.json
>    "fontOverride": "*新機能*  カスタムフォントを使用する",
```suggestion
  "fontOverride": "カスタムフォントを使用する",
```
Same here.

2021-04-20 20:46 UTC, Bl4Cc4t commented on i18n/ja.json
>    "enableQuickBlock": "*新機能* クイックブロックを有効化",
```suggestion
  "enableQuickBlock": "クイックブロックを有効化",
```

2021-04-20 20:46 UTC, Bl4Cc4t commented on i18n/ja.json
> +  "tweetIconsPullLeft": "*新機能* ツイートアイコンを左に寄せる",
```suggestion
  "tweetIconsPullLeft": "ツイートアイコンを左に寄せる",
```

2021-04-21 07:14 UTC, Gizel-jiz commented
Oh, so that's what happened!
I thought it would be reflected in the settings section, since "NEW" was also translated in the previous translation by someone else.
Before the previous translation (i.e. by me), I had deleted the "NEW" part and submitted a pull request.

Thank you for the correction.
I'll remove the "NEW" as before next time.

2021-04-21 21:34 UTC, Bl4Cc4t commented
It looks like you clicked the wrong buttons, the `*NEW*`s are still in the json :D

2021-04-22 04:11 UTC, Gizel-jiz commented
Oh, I'm very sorry.
Could you please reflect the correction there?
I'm sorry for the inconvenience.

2021-04-22 05:58 UTC, Bl4Cc4t requested changes

2021-04-22 05:58 UTC, Bl4Cc4t commented on i18n/ja.json
> +  "settingsHeaderGlobalLook": "*NEW* 全体的な見た目",
```suggestion
  "settingsHeaderGlobalLook": "全体的な見た目",
```

2021-04-22 05:58 UTC, Bl4Cc4t commented on i18n/ja.json
>    "fontOverride": "*新機能*  カスタムフォントを使用する",
```suggestion
  "fontOverride": "カスタムフォントを使用する",
```

2021-04-22 05:58 UTC, Bl4Cc4t commented on i18n/ja.json
>    "enableQuickBlock": "*新機能* クイックブロックを有効化",
```suggestion
  "enableQuickBlock": "クイックブロックを有効化",
```

2021-04-22 05:58 UTC, Bl4Cc4t commented on i18n/ja.json
> +  "tweetIconsPullLeft": "*新機能* ツイートアイコンを左に寄せる",
```suggestion
  "tweetIconsPullLeft": "ツイートアイコンを左に寄せる",
```

2021-04-22 06:14 UTC, Bl4Cc4t commented
You need to click on these buttons:
![image](https://user-images.githubusercontent.com/6740726/115664875-bda7ec80-a342-11eb-925b-c32ab048110d.png)

2021-04-22 08:10 UTC, Gizel-jiz commented
Thank you for the explanatory images. And I apologize for the inconvenience.
I've just authenticated your request. Is there a problem here?

2021-04-22 21:00 UTC, Bl4Cc4t commented
Yes! Now you got it!
As always, thanks for your contribution.

2021-04-22 21:00 UTC, merged